language: python
dist: focal
git:
    depth: false
services:
    - docker
addons:
    ssh_known_hosts: github.ibm.com
deploy:
    - provider: script
      script: >-
          set -e; make docker-build-images docker-test-images docker-quality-images deploy
      on:
          all_branches: true
          # only build docker image and push once
          condition: $TOXENV = py313
          # only deploy when pushing to gh repo
          repo: IBM/detect-secrets
matrix:
    include:
        - env: TOXENV=py313
          python: 3.13.5
        - env: TOXENV=py311
          python: 3.11.13
before_install:
    - echo -e "machine github.com\n  login $GH_ACCESS_TOKEN" >> ~/.netrc # Login to GitHub
    - echo -e "machine github.ibm.com\n  login $GHE_ACCESS_TOKEN" >> ~/.netrc # Login to GitHub Enterprise
install:
    - pip install "certifi>=2022.12.07" "setuptools>=65.5.1" tox pipenv
script: make setup-trivy && make setup-cosign && make trivy-scan-python-vulnerabilities && make test
cache:
    directories:
        - $HOME/.cache/pre-commit
        - $HOME/.cache/trivy
        - $HOME/.cache/cosign
